### ISSUE TITLE
Installation of colab utilities  (Documentation)

### ISSUE THREAD

**Issue by skyprince999** [mitmedialab/AI-generated-characters#1]
First of all awesome work! 
Just discovered this excellent resource and trying to recreate it. I faced the following issue while installing the colab_utilities. And had to utilize an alternative method. Documenting it over here. 

This particular installation didn't work for me 

`
!pip install https://github.com/tugstugi/dl-colab-notebooks/archive/colab_utils.zip -y &> /dev/null
`

I had to use the following alternative - 

```
!wget https://github.com/tugstugi/dl-colab-notebooks/archive/colab_utils.zip
!unzip colab_utils.zip

!mv dl-colab-notebooks-colab_utils/dl_colab_notebooks/ .
!mv dl-colab-notebooks-colab_utils/setup.py . 

!pip install pydub
```

I am using Colab (free version) Let me know if I am missing anything

**Comment by valleballe** [comment]
Thanks for bringing this issue to our attention. The error should now be resolved, and we will be closing this issue.
