### ISSUE TITLE
OSError: MoviePy error: the file /content/Wav2Lip/results/result_voice.mp4 could not be found! Please check that you entered the correct path.

### ISSUE THREAD

**Issue by kenchikuliu** [mitmedialab/AI-generated-characters#2]
Animating Character with Driving Video: This might take a few minutes..
/content/first-order-model
/content
Generating speech from text
Lipsyncing Character with Audio
/content/Wav2Lip
/content

---------------------------------------------------------------------------

OSError                                   Traceback (most recent call last)

<ipython-input-10-92e47c4bc039> in <module>()
     30 
     31 # Traceability
---> 32 tracability(final_video_driver)
     33 final_video_driver = "marked.mp4"
     34 get_ipython().system('ffmpeg -i $final_video_driver -i $audio_driver final_generated.mp4 -y &> /dev/null')

3 frames

/usr/local/lib/python3.7/dist-packages/moviepy/video/io/ffmpeg_reader.py in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    270         raise IOError(("MoviePy error: the file %s could not be found!\n"
    271                       "Please check that you entered the correct "
--> 272                       "path.")%filename)
    273 
    274     result = dict()

OSError: MoviePy error: the file /content/Wav2Lip/results/result_voice.mp4 could not be found!
Please check that you entered the correct path.

Could u please tell me why this happened when I use colab to run it?

**Comment by valleballe** [comment]
Hi kenchikuliu, thanks for submitting your issue.

I was able to replicate this error by not recording or uploading an audio track before running the "Generate Character" cell. Please make sure that you have recorded or uploaded an audio clip before you run the "Generate Character" cell.

Let me know if this fixes your issue.

**Comment by czx81** [comment]
Do you know how to fix this problem? I also encounter this problem.
