### ISSUE TITLE
FileNotFoundError: No such file or directory: '/content/first-order-model/vox-cpk.pth.tar'

### ISSUE THREAD

**Issue by MUzairS15** [mitmedialab/AI-generated-characters#3]
<img width="1181" alt="Screenshot 2022-02-20 at 4 44 18 PM" src="https://user-images.githubusercontent.com/79860504/154839822-67977859-435e-488b-8528-7fab0d339125.png">

**Comment by patthai** [comment]
@MUzairS15  You can download the file from https://www.kaggle.com/rkuo2000/first-order-motion-model and put it in the folder.

**Comment by MUzairS15** [comment]
Thanks @patthai  for your quick reply.
Now, I am facing another problem
`MoviePy error: the file /content/Wav2Lip/results/result_voice.mp4 could not be found!`
`result_voice.mp4` should be created automatically right?
