### ISSUE TITLE
A bug in the notebook

### ISSUE THREAD

**Issue by Sreerag-ibtl** [mitmedialab/AI-generated-characters#4]
My workflow included:
- Ran the installation
- Uploaded an image
- Left the text box empty
- Unchecked audio
- Checked video
- Uploaded driving video

When I ran the generate block, the below error occured:

```
OSError                                   Traceback (most recent call last)
[<ipython-input-4-631bb51a4437>](https://localhost:8080/#) in <module>()
     33 
     34 # Traceability
---> 35 tracability(final_video_driver)
     36 final_video_driver = "marked.mp4"
     37 get_ipython().system('ffmpeg -i $final_video_driver -i $audio_driver final_generated.mp4 -y &> /dev/null')

3 frames
[/usr/local/lib/python3.7/dist-packages/moviepy/video/io/ffmpeg_reader.py](https://localhost:8080/#) in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    270         raise IOError(("MoviePy error: the file %s could not be found!\n"
    271                       "Please check that you entered the correct "
--> 272                       "path.")%filename)
    273 
    274     result = dict()

OSError: MoviePy error: the file merged.mp4 could not be found!
Please check that you entered the correct path.
```
I observed that the If block starting from line 28 uses an audio driver. Which is not present.

Is this expected, or am I missing something here? @valleballe

**Comment by kenchikuliu** [comment]
> 

I meet the error too, any solution?

**Comment by valleballe** [comment]
I am unable to replicate your error. Sometimes the algorithm is unable to find the face in uploaded images which makes it unable to proceed. Did you try with other images? Can you share the files that you were unable to generate your video with?
